# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "nvidia"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd" "nvidia"];
    extraModulePackages = [config.boot.kernelPackages.nvidia_x11];
    blacklistedKernelModules = ["amdgpu"];
    #kernelParams = [ "modules_blacklist=amdgpu" ]; # blacklist integerated GPU
    #kernelParams = [ "pci=realloc" ]; # blacklist integerated GPU
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7a8af706-056c-4b9e-8b94-5e1564e6a568";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C359-5E4A";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/0670df8c-635e-4047-a195-266e1ab8a392";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
