Feature: {FEATURE_NAME}
  As a {ROLE}
  I want {CAPABILITY}
  So that {BENEFIT}

  Background:
    Given {COMMON_PRECONDITION}

  Scenario: {SCENARIO_NAME}
    Given {PRECONDITION}
    And {ADDITIONAL_PRECONDITION}
    When {ACTION}
    And {ADDITIONAL_ACTION}
    Then {OUTCOME}
    And {ADDITIONAL_OUTCOME}

  # Note: {IMPLEMENTATION_HINTS}
