#!/usr/bin/env bash

BPURPLE='\033[1;35m' # Bold purple
GREEN='\033[0;32m'   # Green

echo "${BPURPLE}[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Removing running containers..${GREEN}"
docker ps -a -q | xargs -r docker rm -f

echo "${BPURPLE}[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Removing docker images..${GREEN}"
docker image ls -q | xargs -r docker image rm -f

echo "${BPURPLE}[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] Removing volumes..${GREEN}"
docker volume ls -q | xargs -r docker volume rm
