#!/bin/sh

# only hybernate if audio isn't
music_running=$(pw-cli i all 2>&1 | rg running -q)
ssh_connection=$(ss | grep ssh | grep -q ESTAB)
if [[ $ssh_connection -eq 0 && $music_running -eq 0 ]]; then
	systemctl hybernate
	echo "ssh connection: $ssh_connection, music_running: $music_running"
else
	echo "Not hybernating."
	echo "ssh connection: $ssh_connection, music_running: $music_running"
fi
