{ pkgs, ... }: {
  home.packages = [
    pkgs.asdf
    pkgs.bashInteractive
    pkgs.bat
    pkgs.bats
    pkgs.bitwarden-cli
    pkgs.coreutils
    pkgs.cmake
    pkgs.curl
    pkgs.delve
    pkgs.delta
    pkgs.direnv
    pkgs.exa
    pkgs.fd
    pkgs.fish
    pkgs.fzf
    pkgs.gh
    pkgs.glow
    pkgs.gofumpt
    pkgs.golangci-lint
    pkgs.gopls
    pkgs.gotestsum
    pkgs.gox
    pkgs.hey
    pkgs.jq
    pkgs.kind
    pkgs.krew
    pkgs.kubectx
    pkgs.kubebuilder
    pkgs.kubectl
    pkgs.kustomize
    pkgs.lazygit
    pkgs.lua
    pkgs.nil
    pkgs.nix-bash-completions
    pkgs.nixfmt
    pkgs.openresty
    pkgs.operator-sdk
    pkgs.protobuf
    pkgs.protoc-gen-go
    pkgs.yq
    pkgs.ripgrep
    pkgs.shellcheck
    pkgs.stern
    pkgs.tree
    pkgs.watch
    pkgs.watchexec
    pkgs.wget
    pkgs.yarn
    pkgs.yt-dlp
    pkgs.zoxide
  ];
}
